export type CountryRegionOption = {
  value: string;
  en: string;
  zh: string;
};

export const COUNTRY_REGION_OPTIONS: CountryRegionOption[] = [
  { value: "CN", en: "China", zh: "中国" },
  { value: "HK", en: "Hong Kong SAR", zh: "中国香港" },
  { value: "MO", en: "Macao SAR", zh: "中国澳门" },
  { value: "TW", en: "Taiwan", zh: "中国台湾" },
  { value: "US", en: "United States", zh: "美国" },
  { value: "CA", en: "Canada", zh: "加拿大" },
  { value: "MX", en: "Mexico", zh: "墨西哥" },
  { value: "BR", en: "Brazil", zh: "巴西" },
  { value: "AR", en: "Argentina", zh: "阿根廷" },
  { value: "CL", en: "Chile", zh: "智利" },
  { value: "PE", en: "Peru", zh: "秘鲁" },
  { value: "GB", en: "United Kingdom", zh: "英国" },
  { value: "DE", en: "Germany", zh: "德国" },
  { value: "FR", en: "France", zh: "法国" },
  { value: "IT", en: "Italy", zh: "意大利" },
  { value: "ES", en: "Spain", zh: "西班牙" },
  { value: "NL", en: "Netherlands", zh: "荷兰" },
  { value: "BE", en: "Belgium", zh: "比利时" },
  { value: "CH", en: "Switzerland", zh: "瑞士" },
  { value: "SE", en: "Sweden", zh: "瑞典" },
  { value: "NO", en: "Norway", zh: "挪威" },
  { value: "PL", en: "Poland", zh: "波兰" },
  { value: "RU", en: "Russia", zh: "俄罗斯" },
  { value: "TR", en: "Türkiye", zh: "土耳其" },
  { value: "UA", en: "Ukraine", zh: "乌克兰" },
  { value: "AE", en: "United Arab Emirates", zh: "阿联酋" },
  { value: "SA", en: "Saudi Arabia", zh: "沙特阿拉伯" },
  { value: "QA", en: "Qatar", zh: "卡塔尔" },
  { value: "KW", en: "Kuwait", zh: "科威特" },
  { value: "OM", en: "Oman", zh: "阿曼" },
  { value: "EG", en: "Egypt", zh: "埃及" },
  { value: "DZ", en: "Algeria", zh: "阿尔及利亚" },
  { value: "MA", en: "Morocco", zh: "摩洛哥" },
  { value: "NG", en: "Nigeria", zh: "尼日利亚" },
  { value: "ZA", en: "South Africa", zh: "南非" },
  { value: "KE", en: "Kenya", zh: "肯尼亚" },
  { value: "ET", en: "Ethiopia", zh: "埃塞俄比亚" },
  { value: "IN", en: "India", zh: "印度" },
  { value: "PK", en: "Pakistan", zh: "巴基斯坦" },
  { value: "BD", en: "Bangladesh", zh: "孟加拉国" },
  { value: "TH", en: "Thailand", zh: "泰国" },
  { value: "VN", en: "Vietnam", zh: "越南" },
  { value: "MY", en: "Malaysia", zh: "马来西亚" },
  { value: "ID", en: "Indonesia", zh: "印度尼西亚" },
  { value: "PH", en: "Philippines", zh: "菲律宾" },
  { value: "SG", en: "Singapore", zh: "新加坡" },
  { value: "JP", en: "Japan", zh: "日本" },
  { value: "KR", en: "South Korea", zh: "韩国" },
  { value: "KZ", en: "Kazakhstan", zh: "哈萨克斯坦" },
  { value: "AU", en: "Australia", zh: "澳大利亚" },
  { value: "NZ", en: "New Zealand", zh: "新西兰" },
  { value: "OTHER", en: "Other", zh: "其他" },
];

