export type CountryRegionOption = {
  value: string;
  en: string;
  zh: string;
};

export const COUNTRY_REGION_OPTIONS: CountryRegionOption[] = [
  { value: "CN", en: "China", zh: "中国" },
  { value: "HK", en: "Hong Kong SAR", zh: "中国香港" },
  { value: "MO", en: "Macao SAR", zh: "中国澳门" },
  { value: "TW", en: "Taiwan", zh: "中国台湾" },

  { value: "US", en: "United States", zh: "美国" },
  { value: "CA", en: "Canada", zh: "加拿大" },
  { value: "MX", en: "Mexico", zh: "墨西哥" },
  { value: "GT", en: "Guatemala", zh: "危地马拉" },
  { value: "CR", en: "Costa Rica", zh: "哥斯达黎加" },
  { value: "PA", en: "Panama", zh: "巴拿马" },
  { value: "DO", en: "Dominican Republic", zh: "多米尼加共和国" },

  { value: "BR", en: "Brazil", zh: "巴西" },
  { value: "AR", en: "Argentina", zh: "阿根廷" },
  { value: "CL", en: "Chile", zh: "智利" },
  { value: "PE", en: "Peru", zh: "秘鲁" },
  { value: "CO", en: "Colombia", zh: "哥伦比亚" },
  { value: "VE", en: "Venezuela", zh: "委内瑞拉" },
  { value: "EC", en: "Ecuador", zh: "厄瓜多尔" },
  { value: "UY", en: "Uruguay", zh: "乌拉圭" },
  { value: "PY", en: "Paraguay", zh: "巴拉圭" },
  { value: "BO", en: "Bolivia", zh: "玻利维亚" },

  { value: "GB", en: "United Kingdom", zh: "英国" },
  { value: "IE", en: "Ireland", zh: "爱尔兰" },
  { value: "DE", en: "Germany", zh: "德国" },
  { value: "FR", en: "France", zh: "法国" },
  { value: "IT", en: "Italy", zh: "意大利" },
  { value: "ES", en: "Spain", zh: "西班牙" },
  { value: "PT", en: "Portugal", zh: "葡萄牙" },
  { value: "NL", en: "Netherlands", zh: "荷兰" },
  { value: "BE", en: "Belgium", zh: "比利时" },
  { value: "LU", en: "Luxembourg", zh: "卢森堡" },
  { value: "CH", en: "Switzerland", zh: "瑞士" },
  { value: "AT", en: "Austria", zh: "奥地利" },
  { value: "SE", en: "Sweden", zh: "瑞典" },
  { value: "NO", en: "Norway", zh: "挪威" },
  { value: "FI", en: "Finland", zh: "芬兰" },
  { value: "DK", en: "Denmark", zh: "丹麦" },
  { value: "PL", en: "Poland", zh: "波兰" },
  { value: "CZ", en: "Czech Republic", zh: "捷克" },
  { value: "SK", en: "Slovakia", zh: "斯洛伐克" },
  { value: "HU", en: "Hungary", zh: "匈牙利" },
  { value: "RO", en: "Romania", zh: "罗马尼亚" },
  { value: "BG", en: "Bulgaria", zh: "保加利亚" },
  { value: "GR", en: "Greece", zh: "希腊" },
  { value: "HR", en: "Croatia", zh: "克罗地亚" },
  { value: "SI", en: "Slovenia", zh: "斯洛文尼亚" },
  { value: "RS", en: "Serbia", zh: "塞尔维亚" },
  { value: "BY", en: "Belarus", zh: "白俄罗斯" },
  { value: "RU", en: "Russia", zh: "俄罗斯" },
  { value: "TR", en: "Türkiye", zh: "土耳其" },
  { value: "UA", en: "Ukraine", zh: "乌克兰" },

  { value: "AE", en: "United Arab Emirates", zh: "阿联酋" },
  { value: "SA", en: "Saudi Arabia", zh: "沙特阿拉伯" },
  { value: "QA", en: "Qatar", zh: "卡塔尔" },
  { value: "KW", en: "Kuwait", zh: "科威特" },
  { value: "OM", en: "Oman", zh: "阿曼" },
  { value: "BH", en: "Bahrain", zh: "巴林" },
  { value: "JO", en: "Jordan", zh: "约旦" },
  { value: "IQ", en: "Iraq", zh: "伊拉克" },
  { value: "IR", en: "Iran", zh: "伊朗" },
  { value: "IL", en: "Israel", zh: "以色列" },
  { value: "LB", en: "Lebanon", zh: "黎巴嫩" },

  { value: "EG", en: "Egypt", zh: "埃及" },
  { value: "DZ", en: "Algeria", zh: "阿尔及利亚" },
  { value: "MA", en: "Morocco", zh: "摩洛哥" },
  { value: "TN", en: "Tunisia", zh: "突尼斯" },
  { value: "LY", en: "Libya", zh: "利比亚" },
  { value: "NG", en: "Nigeria", zh: "尼日利亚" },
  { value: "ZA", en: "South Africa", zh: "南非" },
  { value: "KE", en: "Kenya", zh: "肯尼亚" },
  { value: "ET", en: "Ethiopia", zh: "埃塞俄比亚" },
  { value: "GH", en: "Ghana", zh: "加纳" },
  { value: "CI", en: "Cote d'Ivoire", zh: "科特迪瓦" },
  { value: "TZ", en: "Tanzania", zh: "坦桑尼亚" },
  { value: "UG", en: "Uganda", zh: "乌干达" },
  { value: "CM", en: "Cameroon", zh: "喀麦隆" },
  { value: "SD", en: "Sudan", zh: "苏丹" },
  { value: "SN", en: "Senegal", zh: "塞内加尔" },
  { value: "AO", en: "Angola", zh: "安哥拉" },

  { value: "IN", en: "India", zh: "印度" },
  { value: "PK", en: "Pakistan", zh: "巴基斯坦" },
  { value: "BD", en: "Bangladesh", zh: "孟加拉国" },
  { value: "LK", en: "Sri Lanka", zh: "斯里兰卡" },
  { value: "NP", en: "Nepal", zh: "尼泊尔" },
  { value: "TH", en: "Thailand", zh: "泰国" },
  { value: "VN", en: "Vietnam", zh: "越南" },
  { value: "MY", en: "Malaysia", zh: "马来西亚" },
  { value: "ID", en: "Indonesia", zh: "印度尼西亚" },
  { value: "PH", en: "Philippines", zh: "菲律宾" },
  { value: "SG", en: "Singapore", zh: "新加坡" },
  { value: "JP", en: "Japan", zh: "日本" },
  { value: "KR", en: "South Korea", zh: "韩国" },
  { value: "MM", en: "Myanmar", zh: "缅甸" },
  { value: "KH", en: "Cambodia", zh: "柬埔寨" },
  { value: "LA", en: "Laos", zh: "老挝" },

  { value: "KZ", en: "Kazakhstan", zh: "哈萨克斯坦" },
  { value: "UZ", en: "Uzbekistan", zh: "乌兹别克斯坦" },
  { value: "TM", en: "Turkmenistan", zh: "土库曼斯坦" },
  { value: "KG", en: "Kyrgyzstan", zh: "吉尔吉斯斯坦" },
  { value: "TJ", en: "Tajikistan", zh: "塔吉克斯坦" },
  { value: "MN", en: "Mongolia", zh: "蒙古" },

  { value: "AU", en: "Australia", zh: "澳大利亚" },
  { value: "NZ", en: "New Zealand", zh: "新西兰" },
  { value: "PG", en: "Papua New Guinea", zh: "巴布亚新几内亚" },
  { value: "FJ", en: "Fiji", zh: "斐济" },
];
